name: PR Notification

on:
  schedule:
    - cron: "0 10 * * 1-5"  # 平日の午前10時に実行
  workflow_dispatch:  # 手動実行

jobs:
  notify-unapproved-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Pull Requests
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          script: |
            const script = require('./actions-scripts/notifyReviewReminder');
            await script(context);
